import os
BASE = r"c:\Users\hoshe\Downloads\HealthGenie-AI-Web-app-main\HealthGenie-AI-Web-app-main"
path2 = os.path.join(BASE, "qa_automation", "tests", "test_security_ui.py")
lines = []
lines.append("import pytest")
lines.append("import json")
lines.append("import sys")
lines.append("import os")
lines.append("sys.path.insert(0, os.path.join(os.path.dirname(__file__), \"..\"))")
lines.append("")
lines.append("from selenium.webdriver.common.by import By")
lines.append("from selenium.webdriver.support.ui import WebDriverWait")
lines.append("from pages.base_page import BASE_URL")
lines.append("")
lines.append("AUTH_DATA = {")
lines.append("    \"state\": {")
lines.append("        \"user\": {\"name\": \"Sec Test User\", \"email\": \"sec@test.com\", \"id\": 777},")
lines.append("        \"isAuthenticated\": True,")
lines.append("        \"hasCompletedOnboarding\": True,")
lines.append("        \"hasCompletedSetup\": True")
lines.append("    },")
lines.append("    \"version\": 0")
lines.append("}")
lines.append("")
lines.append("def inject_auth(driver, base_url):")
lines.append("    driver.get(base_url)")
lines.append("    WebDriverWait(driver, 15).until(")
lines.append("        lambda d: d.execute_script(\"return document.readyState\") == \"complete\"")
lines.append("    )")
lines.append("    driver.execute_script(")
lines.append("        f\"localStorage.setItem(chr(39)healthgenie-authchr(39), JSON.stringify({json.dumps(AUTH_DATA)}))\"")
lines.append("    )")
with open(path2, "w", encoding="utf-8") as f:
    f.write("\n".join(lines))
print("Written:", path2)
